export type userType = {
    id: number,
    username: string,
    avatarUrl?: string,
    gender: number,
    userProfile: string,
    userAccount: string,
    phone: string,
    email: string,
    userStatus: number,
    userRole: number,
    idCode: string,
    tags: string[],
    createTime: Date,
}